name: walkietaskv2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #LOGUERS
  provider: 2.0.1
  shared_preferences: ^0.5.4+3
  permission_handler: ^4.0.0

  #CONEXIONES
  http: ^0.12.0+2
  sqflite: 1.1.8

  #FIREBASE
  cloud_firestore: ^0.14.4
  firebase_messaging: ^7.0.3

  #UTILS
  flutter_slidable: ^0.5.4
  cupertino_icons: ^0.1.2
  flutter_sound: 1.0.6
  audioplayers: 0.13.5
  equatable: ^1.1.0
  amazon_cognito_identity_dart: ^0.0.22
  image_picker: ^0.6.2+1
  fluttertoast: ^3.1.3
  file_picker: 1.4.3+2
  url_launcher: 5.2.7
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/image/LogoW.png"
  adaptive_icon_background: "assets/image/LogoW.png"


flutter:
  uses-material-design: true
  assets:
    - assets/image/
  fonts:
    - family: helveticaneue2
      fonts:
        - asset: assets/HelveticaNeuBold.ttf
          style: normal
    - family: helveticaneue
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeue-Light.ttf
          weight: 700
        - asset: assets/fonts/helveticaneue/HelveticaNeue.ttf
          weight: 700
        - asset: assets/fonts/helveticaneue/HelveticaNeue-Medium.ttf
          weight: 700
        - asset: assets/fonts/helveticaneue/HelveticaNeu-Bold.ttf
          weight: 700
    - family: helveticaneue-Regular
      fonts:
        - asset: assets/fonts/helveticaneue/helveticaneue-regular.ttf
          weight: 700
    - family: HelveticaNeu-Bold
      fonts:
        - asset: assets/fonts/helveticaneue/HelveticaNeu-Bold.ttf
          weight: 700
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 700
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
    - family: Nunito-Black
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 700
    - family: Avenir-Book
      fonts:
        - asset: assets/fonts/Avenir/Avenir-Book.otf
          weight: 700